name: Build to .exe

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  exe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup GCC 🪄
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Build 🚀
        run: |
          bash ./scripts/build2exe.sh
